# Generated by Django 5.0.1 on 2024-06-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addexpense',
            name='category',
            field=models.TextField(default='Uncategorised', max_length=20),
            preserve_default=False,
        ),
    ]
